name: Testing
run-name: ${{ github.actor }} is testing.
on: [push]
jobs:
  CodeTesting:
    runs-on: ubuntu-latest
    container: alexchenqr/python-crypto-arbitrage-bot:latest # 使用自定义的Docker image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: python3 main.py
      - run: echo "This job's status is ${{ job.status }}."